/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Algorithms;

import javax.swing.JTextField;

/**
 *
 * @author Ashani Dikowita
 */
public class InsertionSort extends javax.swing.JFrame {

    /**
     * Creates new form InsertionSort
     */
    public InsertionSort() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InsertionSortjPanel2 = new javax.swing.JPanel();
        ArrayElement0jTextField2 = new javax.swing.JTextField();
        ArrayElement1jTextField2 = new javax.swing.JTextField();
        ArrayElement2jTextField2 = new javax.swing.JTextField();
        ArrayElement3jTextField2 = new javax.swing.JTextField();
        ArrayElement4jTextField2 = new javax.swing.JTextField();
        ISSortjButton2 = new javax.swing.JButton();
        ArraysortedstepArrayElement0jTextField2 = new javax.swing.JTextField();
        ArraysortedstepArrayElement1jTextField2 = new javax.swing.JTextField();
        ArraysortedstepArrayElement2jTextField2 = new javax.swing.JTextField();
        ArraysortedstepArrayElement3jTextField2 = new javax.swing.JTextField();
        ArraysortedstepArrayElement4jTextField2 = new javax.swing.JTextField();
        SortedarrayjLabel2 = new javax.swing.JLabel();
        keyElement1jTextField2 = new javax.swing.JTextField();
        key1jLabel2 = new javax.swing.JLabel();
        key2jLabel4 = new javax.swing.JLabel();
        keyElement2jTextField2 = new javax.swing.JTextField();
        key3jLabel3 = new javax.swing.JLabel();
        key4jLabel3 = new javax.swing.JLabel();
        key2jLabel5 = new javax.swing.JLabel();
        keyElement3jTextField2 = new javax.swing.JTextField();
        keyElement4jTextField2 = new javax.swing.JTextField();
        Arraysortedstep1ArrayElement0jTextField2 = new javax.swing.JTextField();
        Arraysortedstep1ArrayElement1jTextField2 = new javax.swing.JTextField();
        Arraysortedstep1ArrayElement2jTextField2 = new javax.swing.JTextField();
        Arraysortedstep1ArrayElement3jTextField2 = new javax.swing.JTextField();
        Arraysortedstep1ArrayElement4jTextField2 = new javax.swing.JTextField();
        Arraysortedstep2ArrayElement0jTextField2 = new javax.swing.JTextField();
        Arraysortedstep2ArrayElement1jTextField2 = new javax.swing.JTextField();
        Arraysortedstep2ArrayElement2jTextField2 = new javax.swing.JTextField();
        Arraysortedstep2ArrayElement3jTextField2 = new javax.swing.JTextField();
        Arraysortedstep2ArrayElement4jTextField2 = new javax.swing.JTextField();
        Arraysortedstep3ArrayElement0jTextField2 = new javax.swing.JTextField();
        Arraysortedstep3ArrayElement1jTextField2 = new javax.swing.JTextField();
        Arraysortedstep3ArrayElement2jTextField2 = new javax.swing.JTextField();
        Arraysortedstep3ArrayElement3jTextField2 = new javax.swing.JTextField();
        Arraysortedstep3ArrayElement4jTextField2 = new javax.swing.JTextField();
        Step1jLabel2 = new javax.swing.JLabel();
        Step2jLabel2 = new javax.swing.JLabel();
        step3jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BackjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ClearjButton = new javax.swing.JButton();
        ShowISAlgorithmjButton = new javax.swing.JButton();
        ISSortDemojButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        InsertionSortjPanel2.setBackground(new java.awt.Color(255, 255, 255));
        InsertionSortjPanel2.setPreferredSize(new java.awt.Dimension(1024, 700));

        ArrayElement0jTextField2.setBackground(new java.awt.Color(153, 255, 153));
        ArrayElement0jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArrayElement0jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        ArrayElement1jTextField2.setBackground(new java.awt.Color(153, 255, 153));
        ArrayElement1jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArrayElement1jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ArrayElement1jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrayElement1jTextField2ActionPerformed(evt);
            }
        });

        ArrayElement2jTextField2.setBackground(new java.awt.Color(153, 255, 153));
        ArrayElement2jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArrayElement2jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        ArrayElement3jTextField2.setBackground(new java.awt.Color(153, 255, 153));
        ArrayElement3jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArrayElement3jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ArrayElement3jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrayElement3jTextField2ActionPerformed(evt);
            }
        });

        ArrayElement4jTextField2.setBackground(new java.awt.Color(153, 255, 153));
        ArrayElement4jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArrayElement4jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        ISSortjButton2.setBackground(new java.awt.Color(51, 153, 255));
        ISSortjButton2.setForeground(new java.awt.Color(255, 255, 255));
        ISSortjButton2.setText("Insertion Sort");
        ISSortjButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ISSortjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISSortjButton2ActionPerformed(evt);
            }
        });

        ArraysortedstepArrayElement0jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        ArraysortedstepArrayElement0jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArraysortedstepArrayElement0jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ArraysortedstepArrayElement0jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArraysortedstepArrayElement0jTextField2ActionPerformed(evt);
            }
        });

        ArraysortedstepArrayElement1jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        ArraysortedstepArrayElement1jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArraysortedstepArrayElement1jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ArraysortedstepArrayElement1jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArraysortedstepArrayElement1jTextField2ActionPerformed(evt);
            }
        });

        ArraysortedstepArrayElement2jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        ArraysortedstepArrayElement2jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArraysortedstepArrayElement2jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        ArraysortedstepArrayElement3jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        ArraysortedstepArrayElement3jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArraysortedstepArrayElement3jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ArraysortedstepArrayElement3jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArraysortedstepArrayElement3jTextField2ActionPerformed(evt);
            }
        });

        ArraysortedstepArrayElement4jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        ArraysortedstepArrayElement4jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArraysortedstepArrayElement4jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        SortedarrayjLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        SortedarrayjLabel2.setText("Sorted Array");

        keyElement1jTextField2.setBackground(new java.awt.Color(255, 153, 153));
        keyElement1jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        keyElement1jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        key1jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        key1jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        key1jLabel2.setText("Key 1");

        key2jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        key2jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        key2jLabel4.setText("key 2");

        keyElement2jTextField2.setBackground(new java.awt.Color(255, 153, 153));
        keyElement2jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        keyElement2jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        key3jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        key3jLabel3.setText("Key 3");

        key4jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        key4jLabel3.setText("key 4");

        keyElement3jTextField2.setBackground(new java.awt.Color(255, 153, 153));
        keyElement3jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        keyElement3jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        keyElement3jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyElement3jTextField2ActionPerformed(evt);
            }
        });

        keyElement4jTextField2.setBackground(new java.awt.Color(255, 153, 153));
        keyElement4jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        keyElement4jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Arraysortedstep1ArrayElement0jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        Arraysortedstep1ArrayElement0jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep1ArrayElement0jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Arraysortedstep1ArrayElement0jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arraysortedstep1ArrayElement0jTextField2ActionPerformed(evt);
            }
        });

        Arraysortedstep1ArrayElement1jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        Arraysortedstep1ArrayElement1jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep1ArrayElement1jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Arraysortedstep1ArrayElement1jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arraysortedstep1ArrayElement1jTextField2ActionPerformed(evt);
            }
        });

        Arraysortedstep1ArrayElement2jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep1ArrayElement2jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Arraysortedstep1ArrayElement3jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep1ArrayElement3jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Arraysortedstep1ArrayElement3jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arraysortedstep1ArrayElement3jTextField2ActionPerformed(evt);
            }
        });

        Arraysortedstep1ArrayElement4jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep1ArrayElement4jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Arraysortedstep2ArrayElement0jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        Arraysortedstep2ArrayElement0jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep2ArrayElement0jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Arraysortedstep2ArrayElement0jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arraysortedstep2ArrayElement0jTextField2ActionPerformed(evt);
            }
        });

        Arraysortedstep2ArrayElement1jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        Arraysortedstep2ArrayElement1jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep2ArrayElement1jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Arraysortedstep2ArrayElement1jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arraysortedstep2ArrayElement1jTextField2ActionPerformed(evt);
            }
        });

        Arraysortedstep2ArrayElement2jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        Arraysortedstep2ArrayElement2jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep2ArrayElement2jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Arraysortedstep2ArrayElement3jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep2ArrayElement3jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Arraysortedstep2ArrayElement3jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arraysortedstep2ArrayElement3jTextField2ActionPerformed(evt);
            }
        });

        Arraysortedstep2ArrayElement4jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep2ArrayElement4jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Arraysortedstep3ArrayElement0jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        Arraysortedstep3ArrayElement0jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep3ArrayElement0jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Arraysortedstep3ArrayElement0jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arraysortedstep3ArrayElement0jTextField2ActionPerformed(evt);
            }
        });

        Arraysortedstep3ArrayElement1jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        Arraysortedstep3ArrayElement1jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep3ArrayElement1jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Arraysortedstep3ArrayElement1jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arraysortedstep3ArrayElement1jTextField2ActionPerformed(evt);
            }
        });

        Arraysortedstep3ArrayElement2jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        Arraysortedstep3ArrayElement2jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep3ArrayElement2jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Arraysortedstep3ArrayElement3jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        Arraysortedstep3ArrayElement3jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep3ArrayElement3jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Arraysortedstep3ArrayElement3jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Arraysortedstep3ArrayElement3jTextField2ActionPerformed(evt);
            }
        });

        Arraysortedstep3ArrayElement4jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Arraysortedstep3ArrayElement4jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Step1jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Step1jLabel2.setText("Step 1");

        Step2jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Step2jLabel2.setText("Step 2");

        step3jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        step3jLabel2.setText("Step 3");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Enter the values to sort below");

        BackjButton.setBackground(new java.awt.Color(51, 153, 255));
        BackjButton.setForeground(new java.awt.Color(255, 255, 255));
        BackjButton.setText("Back");
        BackjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Insertion Sort");

        ClearjButton.setBackground(new java.awt.Color(51, 153, 255));
        ClearjButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearjButton.setText("Clear");
        ClearjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ClearjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearjButtonActionPerformed(evt);
            }
        });

        ShowISAlgorithmjButton.setBackground(new java.awt.Color(51, 153, 255));
        ShowISAlgorithmjButton.setForeground(new java.awt.Color(255, 255, 255));
        ShowISAlgorithmjButton.setText("Show Algorithm");
        ShowISAlgorithmjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ShowISAlgorithmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowISAlgorithmjButtonActionPerformed(evt);
            }
        });

        ISSortDemojButton.setBackground(new java.awt.Color(51, 153, 255));
        ISSortDemojButton.setForeground(new java.awt.Color(255, 255, 255));
        ISSortDemojButton.setText("Demo");
        ISSortDemojButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ISSortDemojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISSortDemojButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InsertionSortjPanel2Layout = new javax.swing.GroupLayout(InsertionSortjPanel2);
        InsertionSortjPanel2.setLayout(InsertionSortjPanel2Layout);
        InsertionSortjPanel2Layout.setHorizontalGroup(
            InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                        .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(key4jLabel3)
                            .addComponent(key2jLabel4)
                            .addComponent(key3jLabel3))
                        .addGap(39, 39, 39))
                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                        .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(key1jLabel2)
                            .addComponent(Step1jLabel2)
                            .addComponent(Step2jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SortedarrayjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(step3jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(keyElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                                        .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Arraysortedstep2ArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(keyElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addComponent(Arraysortedstep2ArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(Arraysortedstep2ArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(Arraysortedstep2ArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(Arraysortedstep2ArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                                        .addComponent(Arraysortedstep3ArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(Arraysortedstep3ArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(Arraysortedstep3ArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(Arraysortedstep3ArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(Arraysortedstep3ArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(keyElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                                        .addComponent(ArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(ArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(ArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                                        .addComponent(Arraysortedstep1ArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(Arraysortedstep1ArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(Arraysortedstep1ArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Arraysortedstep1ArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Arraysortedstep1ArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                                        .addComponent(ArraysortedstepArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ShowISAlgorithmjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                                                .addComponent(ArraysortedstepArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(ArraysortedstepArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(ArraysortedstepArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(ArraysortedstepArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 99, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InsertionSortjPanel2Layout.createSequentialGroup()
                                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                                        .addComponent(keyElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ISSortDemojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(ISSortjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                                                .addComponent(ClearjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(49, 49, 49)
                                                .addComponent(BackjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(70, 70, 70)))
                        .addComponent(key2jLabel5)
                        .addContainerGap(49, Short.MAX_VALUE))))
            .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        InsertionSortjPanel2Layout.setVerticalGroup(
            InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3))
                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)))
                .addGap(50, 50, 50)
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(keyElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(key1jLabel2)
                            .addComponent(key2jLabel5)))
                    .addGroup(InsertionSortjPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ISSortjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ISSortDemojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Arraysortedstep1ArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep1ArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep1ArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep1ArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep1ArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Step1jLabel2))
                .addGap(30, 30, 30)
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key2jLabel4)
                    .addComponent(keyElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Arraysortedstep2ArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep2ArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep2ArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep2ArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep2ArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Step2jLabel2))
                .addGap(30, 30, 30)
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key3jLabel3)
                    .addComponent(keyElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Arraysortedstep3ArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep3ArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep3ArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep3ArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Arraysortedstep3ArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(step3jLabel2))
                .addGap(30, 30, 30)
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(key4jLabel3)
                    .addComponent(keyElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ArraysortedstepArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArraysortedstepArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArraysortedstepArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArraysortedstepArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArraysortedstepArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SortedarrayjLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(InsertionSortjPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowISAlgorithmjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InsertionSortjPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InsertionSortjPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArrayElement1jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrayElement1jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArrayElement1jTextField2ActionPerformed

    private void ArrayElement3jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrayElement3jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArrayElement3jTextField2ActionPerformed

    private void ISSortjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISSortjButton2ActionPerformed
        try{
           
            JTextField Array1[];//step 1 elements

            Array1 = new JTextField[]{Arraysortedstep1ArrayElement0jTextField2,Arraysortedstep1ArrayElement1jTextField2,Arraysortedstep1ArrayElement2jTextField2,
                Arraysortedstep1ArrayElement3jTextField2,Arraysortedstep1ArrayElement4jTextField2};

            JTextField Array2[];//step 2 elements

            Array2 = new JTextField[]{Arraysortedstep2ArrayElement0jTextField2,Arraysortedstep2ArrayElement1jTextField2,Arraysortedstep2ArrayElement2jTextField2,
                Arraysortedstep2ArrayElement3jTextField2,Arraysortedstep2ArrayElement4jTextField2};

            JTextField Array3[];//step 3 elements

            Array3 = new JTextField[]{Arraysortedstep3ArrayElement0jTextField2,Arraysortedstep3ArrayElement1jTextField2,Arraysortedstep3ArrayElement2jTextField2,
                Arraysortedstep3ArrayElement3jTextField2,Arraysortedstep3ArrayElement4jTextField2};

            int sortArray[]=new int[5];//elements that are entered by the user

            sortArray[0]=Integer.parseInt(ArrayElement0jTextField2.getText());
            sortArray[1]=Integer.parseInt(ArrayElement1jTextField2.getText());
            sortArray[2]=Integer.parseInt(ArrayElement2jTextField2.getText());
            sortArray[3]=Integer.parseInt(ArrayElement3jTextField2.getText());
            sortArray[4]=Integer.parseInt(ArrayElement4jTextField2.getText());

            int i,j,key;//insertion sort algorithm
            for(j=1;j<sortArray.length;j++)
            {
                key=sortArray[j];
                i=j-1;

                while (i>=0 && sortArray[i]>key)
                {
                    sortArray[i+1]=sortArray[i];
                    i=i-1;
                }
                sortArray[i+1]=key;

                if(j==1)
                {
                    keyElement1jTextField2.setText(Integer.toString(key));
                    for(int m=0;m<Array1.length;m++)
                    {
                        Array1[m].setText(Integer.toString(sortArray[m]));
                    }
                }
                if(j==2)
                {
                    keyElement2jTextField2.setText(Integer.toString(key));
                    for(int m=0;m<Array2.length;m++)
                    {
                        Array2[m].setText(Integer.toString(sortArray[m]));
                    }
                }
                if(j==3)
                {
                    keyElement3jTextField2.setText(Integer.toString(key));
                    for(int m=0;m<Array3.length;m++)
                    {
                        Array3[m].setText(Integer.toString(sortArray[m]));
                    }
                }
                if(j==4)
                {
                    keyElement4jTextField2.setText(Integer.toString(key));
                }

            }
            for(int m=0;m<sortArray.length;m++)
            {
                ArraysortedstepArrayElement0jTextField2.setText(Integer.toString(sortArray[0]));
                ArraysortedstepArrayElement1jTextField2.setText(Integer.toString(sortArray[1]));
                ArraysortedstepArrayElement2jTextField2.setText(Integer.toString(sortArray[2]));
                ArraysortedstepArrayElement3jTextField2.setText(Integer.toString(sortArray[3]));
                ArraysortedstepArrayElement4jTextField2.setText(Integer.toString(sortArray[4]));
            }

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_ISSortjButton2ActionPerformed

    private void ArraysortedstepArrayElement0jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArraysortedstepArrayElement0jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArraysortedstepArrayElement0jTextField2ActionPerformed

    private void ArraysortedstepArrayElement1jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArraysortedstepArrayElement1jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArraysortedstepArrayElement1jTextField2ActionPerformed

    private void ArraysortedstepArrayElement3jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArraysortedstepArrayElement3jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArraysortedstepArrayElement3jTextField2ActionPerformed

    private void keyElement3jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyElement3jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keyElement3jTextField2ActionPerformed

    private void Arraysortedstep1ArrayElement0jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arraysortedstep1ArrayElement0jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arraysortedstep1ArrayElement0jTextField2ActionPerformed

    private void Arraysortedstep1ArrayElement1jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arraysortedstep1ArrayElement1jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arraysortedstep1ArrayElement1jTextField2ActionPerformed

    private void Arraysortedstep1ArrayElement3jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arraysortedstep1ArrayElement3jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arraysortedstep1ArrayElement3jTextField2ActionPerformed

    private void Arraysortedstep2ArrayElement0jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arraysortedstep2ArrayElement0jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arraysortedstep2ArrayElement0jTextField2ActionPerformed

    private void Arraysortedstep2ArrayElement1jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arraysortedstep2ArrayElement1jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arraysortedstep2ArrayElement1jTextField2ActionPerformed

    private void Arraysortedstep2ArrayElement3jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arraysortedstep2ArrayElement3jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arraysortedstep2ArrayElement3jTextField2ActionPerformed

    private void Arraysortedstep3ArrayElement0jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arraysortedstep3ArrayElement0jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arraysortedstep3ArrayElement0jTextField2ActionPerformed

    private void Arraysortedstep3ArrayElement1jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arraysortedstep3ArrayElement1jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arraysortedstep3ArrayElement1jTextField2ActionPerformed

    private void Arraysortedstep3ArrayElement3jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Arraysortedstep3ArrayElement3jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Arraysortedstep3ArrayElement3jTextField2ActionPerformed

    private void BackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButtonActionPerformed
        MainAlgorithm ma1 = new MainAlgorithm();
        ma1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackjButtonActionPerformed

    private void ClearjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearjButtonActionPerformed
     ArrayElement0jTextField2.setText("");
     ArrayElement1jTextField2.setText("");
     ArrayElement2jTextField2.setText("");
     ArrayElement3jTextField2.setText("");
     ArrayElement4jTextField2.setText("");
     Arraysortedstep1ArrayElement0jTextField2.setText("");
     Arraysortedstep1ArrayElement1jTextField2.setText("");
     Arraysortedstep1ArrayElement2jTextField2.setText("");
     Arraysortedstep1ArrayElement3jTextField2.setText("");
     Arraysortedstep1ArrayElement4jTextField2.setText("");
     Arraysortedstep2ArrayElement0jTextField2.setText("");
     Arraysortedstep2ArrayElement1jTextField2.setText("");
     Arraysortedstep2ArrayElement2jTextField2.setText("");
     Arraysortedstep2ArrayElement3jTextField2.setText("");
     Arraysortedstep2ArrayElement4jTextField2.setText("");
     Arraysortedstep3ArrayElement0jTextField2.setText("");
     Arraysortedstep3ArrayElement1jTextField2.setText("");
     Arraysortedstep3ArrayElement2jTextField2.setText("");
     Arraysortedstep3ArrayElement3jTextField2.setText("");
     Arraysortedstep3ArrayElement4jTextField2.setText("");
     ArraysortedstepArrayElement0jTextField2.setText("");
     ArraysortedstepArrayElement1jTextField2.setText("");
     ArraysortedstepArrayElement2jTextField2.setText("");
     ArraysortedstepArrayElement3jTextField2.setText("");
     ArraysortedstepArrayElement4jTextField2.setText("");
     keyElement1jTextField2.setText("");
     keyElement2jTextField2.setText("");
     keyElement3jTextField2.setText("");
     keyElement4jTextField2.setText("");
    }//GEN-LAST:event_ClearjButtonActionPerformed

    private void ShowISAlgorithmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowISAlgorithmjButtonActionPerformed
        AlgorithmIS A1=new AlgorithmIS();
        A1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ShowISAlgorithmjButtonActionPerformed

    private void ISSortDemojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISSortDemojButtonActionPerformed
     ArrayElement0jTextField2.setText("4");
     ArrayElement1jTextField2.setText("2");
     ArrayElement2jTextField2.setText("5");
     ArrayElement3jTextField2.setText("3");
     ArrayElement4jTextField2.setText("9");  
    }//GEN-LAST:event_ISSortDemojButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertionSort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArrayElement0jTextField2;
    private javax.swing.JTextField ArrayElement1jTextField2;
    private javax.swing.JTextField ArrayElement2jTextField2;
    private javax.swing.JTextField ArrayElement3jTextField2;
    private javax.swing.JTextField ArrayElement4jTextField2;
    private javax.swing.JTextField Arraysortedstep1ArrayElement0jTextField2;
    private javax.swing.JTextField Arraysortedstep1ArrayElement1jTextField2;
    private javax.swing.JTextField Arraysortedstep1ArrayElement2jTextField2;
    private javax.swing.JTextField Arraysortedstep1ArrayElement3jTextField2;
    private javax.swing.JTextField Arraysortedstep1ArrayElement4jTextField2;
    private javax.swing.JTextField Arraysortedstep2ArrayElement0jTextField2;
    private javax.swing.JTextField Arraysortedstep2ArrayElement1jTextField2;
    private javax.swing.JTextField Arraysortedstep2ArrayElement2jTextField2;
    private javax.swing.JTextField Arraysortedstep2ArrayElement3jTextField2;
    private javax.swing.JTextField Arraysortedstep2ArrayElement4jTextField2;
    private javax.swing.JTextField Arraysortedstep3ArrayElement0jTextField2;
    private javax.swing.JTextField Arraysortedstep3ArrayElement1jTextField2;
    private javax.swing.JTextField Arraysortedstep3ArrayElement2jTextField2;
    private javax.swing.JTextField Arraysortedstep3ArrayElement3jTextField2;
    private javax.swing.JTextField Arraysortedstep3ArrayElement4jTextField2;
    private javax.swing.JTextField ArraysortedstepArrayElement0jTextField2;
    private javax.swing.JTextField ArraysortedstepArrayElement1jTextField2;
    private javax.swing.JTextField ArraysortedstepArrayElement2jTextField2;
    private javax.swing.JTextField ArraysortedstepArrayElement3jTextField2;
    private javax.swing.JTextField ArraysortedstepArrayElement4jTextField2;
    private javax.swing.JButton BackjButton;
    private javax.swing.JButton ClearjButton;
    private javax.swing.JButton ISSortDemojButton;
    private javax.swing.JButton ISSortjButton2;
    private javax.swing.JPanel InsertionSortjPanel2;
    private javax.swing.JButton ShowISAlgorithmjButton;
    private javax.swing.JLabel SortedarrayjLabel2;
    private javax.swing.JLabel Step1jLabel2;
    private javax.swing.JLabel Step2jLabel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel key1jLabel2;
    private javax.swing.JLabel key2jLabel4;
    private javax.swing.JLabel key2jLabel5;
    private javax.swing.JLabel key3jLabel3;
    private javax.swing.JLabel key4jLabel3;
    private javax.swing.JTextField keyElement1jTextField2;
    private javax.swing.JTextField keyElement2jTextField2;
    private javax.swing.JTextField keyElement3jTextField2;
    private javax.swing.JTextField keyElement4jTextField2;
    private javax.swing.JLabel step3jLabel2;
    // End of variables declaration//GEN-END:variables
}
