/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Algorithms;

/**
 *
 * @author Ashani Dikowita
 */
public class MainAlgorithm extends javax.swing.JFrame {

    /**
     * Creates new form MainAlgorithm
     */
    public MainAlgorithm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainAlgorithmjPanel = new javax.swing.JPanel();
        InsertionsortjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        InsertionsortjButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainAlgorithmjPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainAlgorithmjPanel.setPreferredSize(new java.awt.Dimension(1024, 700));

        InsertionsortjButton.setBackground(new java.awt.Color(51, 153, 255));
        InsertionsortjButton.setForeground(new java.awt.Color(255, 255, 255));
        InsertionsortjButton.setText("Insertion Sort");
        InsertionsortjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        InsertionsortjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertionsortjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Choose the Sorting Method!!");

        InsertionsortjButton1.setBackground(new java.awt.Color(51, 153, 255));
        InsertionsortjButton1.setForeground(new java.awt.Color(255, 255, 255));
        InsertionsortjButton1.setText("Selection Sort");
        InsertionsortjButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        InsertionsortjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertionsortjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainAlgorithmjPanelLayout = new javax.swing.GroupLayout(MainAlgorithmjPanel);
        MainAlgorithmjPanel.setLayout(MainAlgorithmjPanelLayout);
        MainAlgorithmjPanelLayout.setHorizontalGroup(
            MainAlgorithmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainAlgorithmjPanelLayout.createSequentialGroup()
                .addGroup(MainAlgorithmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainAlgorithmjPanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1))
                    .addGroup(MainAlgorithmjPanelLayout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addGroup(MainAlgorithmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(InsertionsortjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InsertionsortjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainAlgorithmjPanelLayout.setVerticalGroup(
            MainAlgorithmjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainAlgorithmjPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jLabel1)
                .addGap(95, 95, 95)
                .addComponent(InsertionsortjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(InsertionsortjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainAlgorithmjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainAlgorithmjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertionsortjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertionsortjButtonActionPerformed
        InsertionSort isort = new InsertionSort();
        isort.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InsertionsortjButtonActionPerformed

    private void InsertionsortjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertionsortjButton1ActionPerformed
        SelectionSort ssort = new SelectionSort();
        ssort.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_InsertionsortjButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAlgorithm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAlgorithm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InsertionsortjButton;
    private javax.swing.JButton InsertionsortjButton1;
    private javax.swing.JPanel MainAlgorithmjPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
