/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Algorithms;

import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author Ashani Dikowita
 */
public class SelectionSort extends javax.swing.JFrame {

    /**
     * Creates new form SelectionSort
     */
    public SelectionSort() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectionSortjPanel = new javax.swing.JPanel();
        ArrayElement0jTextField2 = new javax.swing.JTextField();
        ArrayElement1jTextField2 = new javax.swing.JTextField();
        ArrayElement2jTextField2 = new javax.swing.JTextField();
        ArrayElement3jTextField2 = new javax.swing.JTextField();
        ArrayElement4jTextField2 = new javax.swing.JTextField();
        sSortjButton2 = new javax.swing.JButton();
        ssArraysortedstepArrayElement0jTextField2 = new javax.swing.JTextField();
        ssArraysortedstepArrayElement1jTextField2 = new javax.swing.JTextField();
        ssArraysortedstepArrayElement2jTextField2 = new javax.swing.JTextField();
        ssArraysortedstepArrayElement3jTextField2 = new javax.swing.JTextField();
        ssArraysortedstepArrayElement4jTextField2 = new javax.swing.JTextField();
        SortedarrayjLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BackjButton = new javax.swing.JButton();
        smallElementjTextField = new javax.swing.JTextField();
        smallElementjTextField1 = new javax.swing.JTextField();
        smallElementjTextField2 = new javax.swing.JTextField();
        smallElementjTextField3 = new javax.swing.JTextField();
        Step1ArrayElement0jTextField = new javax.swing.JTextField();
        Step1ArrayElement1jTextField = new javax.swing.JTextField();
        Step1ArrayElement2jTextField = new javax.swing.JTextField();
        Step1ArrayElement3jTextField = new javax.swing.JTextField();
        Step1ArrayElement4jTextField = new javax.swing.JTextField();
        Step2ArrayElement0jTextField = new javax.swing.JTextField();
        Step2ArrayElement1jTextField = new javax.swing.JTextField();
        Step2ArrayElement2jTextField = new javax.swing.JTextField();
        Step2ArrayElement3jTextField = new javax.swing.JTextField();
        Step2ArrayElement4jTextField = new javax.swing.JTextField();
        Step3ArrayElement0jTextField = new javax.swing.JTextField();
        Step3ArrayElement1jTextField = new javax.swing.JTextField();
        Step3ArrayElement2jTextField = new javax.swing.JTextField();
        Step3ArrayElement3jTextField = new javax.swing.JTextField();
        Step3ArrayElement4jTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        key4jLabel3 = new javax.swing.JLabel();
        step3jLabel2 = new javax.swing.JLabel();
        key3jLabel3 = new javax.swing.JLabel();
        Step2jLabel2 = new javax.swing.JLabel();
        key2jLabel4 = new javax.swing.JLabel();
        Step1jLabel2 = new javax.swing.JLabel();
        key1jLabel2 = new javax.swing.JLabel();
        ClearjButton = new javax.swing.JButton();
        ShowSSAlgorithmjButton = new javax.swing.JButton();
        sSortdemojButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        SelectionSortjPanel.setBackground(new java.awt.Color(255, 255, 255));
        SelectionSortjPanel.setPreferredSize(new java.awt.Dimension(1024, 700));

        ArrayElement0jTextField2.setBackground(new java.awt.Color(153, 255, 153));
        ArrayElement0jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArrayElement0jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        ArrayElement1jTextField2.setBackground(new java.awt.Color(153, 255, 153));
        ArrayElement1jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArrayElement1jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ArrayElement1jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrayElement1jTextField2ActionPerformed(evt);
            }
        });

        ArrayElement2jTextField2.setBackground(new java.awt.Color(153, 255, 153));
        ArrayElement2jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArrayElement2jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        ArrayElement3jTextField2.setBackground(new java.awt.Color(153, 255, 153));
        ArrayElement3jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArrayElement3jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ArrayElement3jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrayElement3jTextField2ActionPerformed(evt);
            }
        });

        ArrayElement4jTextField2.setBackground(new java.awt.Color(153, 255, 153));
        ArrayElement4jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ArrayElement4jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        sSortjButton2.setBackground(new java.awt.Color(51, 153, 255));
        sSortjButton2.setForeground(new java.awt.Color(255, 255, 255));
        sSortjButton2.setText("Selection Sort");
        sSortjButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sSortjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSortjButton2ActionPerformed(evt);
            }
        });

        ssArraysortedstepArrayElement0jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        ssArraysortedstepArrayElement0jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ssArraysortedstepArrayElement0jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ssArraysortedstepArrayElement0jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssArraysortedstepArrayElement0jTextField2ActionPerformed(evt);
            }
        });

        ssArraysortedstepArrayElement1jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        ssArraysortedstepArrayElement1jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ssArraysortedstepArrayElement1jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ssArraysortedstepArrayElement1jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssArraysortedstepArrayElement1jTextField2ActionPerformed(evt);
            }
        });

        ssArraysortedstepArrayElement2jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        ssArraysortedstepArrayElement2jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ssArraysortedstepArrayElement2jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        ssArraysortedstepArrayElement3jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        ssArraysortedstepArrayElement3jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ssArraysortedstepArrayElement3jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ssArraysortedstepArrayElement3jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssArraysortedstepArrayElement3jTextField2ActionPerformed(evt);
            }
        });

        ssArraysortedstepArrayElement4jTextField2.setBackground(new java.awt.Color(153, 204, 255));
        ssArraysortedstepArrayElement4jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ssArraysortedstepArrayElement4jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        SortedarrayjLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        SortedarrayjLabel2.setText("Sorted Array");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Enter the values to sort below");

        BackjButton.setBackground(new java.awt.Color(51, 153, 255));
        BackjButton.setForeground(new java.awt.Color(255, 255, 255));
        BackjButton.setText("Back");
        BackjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BackjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackjButtonActionPerformed(evt);
            }
        });

        smallElementjTextField.setBackground(new java.awt.Color(255, 153, 153));
        smallElementjTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        smallElementjTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        smallElementjTextField1.setBackground(new java.awt.Color(255, 153, 153));
        smallElementjTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        smallElementjTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        smallElementjTextField2.setBackground(new java.awt.Color(255, 153, 153));
        smallElementjTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        smallElementjTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        smallElementjTextField3.setBackground(new java.awt.Color(255, 153, 153));
        smallElementjTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        smallElementjTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Step1ArrayElement0jTextField.setBackground(new java.awt.Color(153, 204, 255));
        Step1ArrayElement0jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step1ArrayElement0jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Step1ArrayElement1jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step1ArrayElement1jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Step1ArrayElement1jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Step1ArrayElement1jTextFieldActionPerformed(evt);
            }
        });

        Step1ArrayElement2jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step1ArrayElement2jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Step1ArrayElement3jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step1ArrayElement3jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Step1ArrayElement3jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Step1ArrayElement3jTextFieldActionPerformed(evt);
            }
        });

        Step1ArrayElement4jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step1ArrayElement4jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Step2ArrayElement0jTextField.setBackground(new java.awt.Color(153, 204, 255));
        Step2ArrayElement0jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step2ArrayElement0jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Step2ArrayElement1jTextField.setBackground(new java.awt.Color(153, 204, 255));
        Step2ArrayElement1jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step2ArrayElement1jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Step2ArrayElement1jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Step2ArrayElement1jTextFieldActionPerformed(evt);
            }
        });

        Step2ArrayElement2jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step2ArrayElement2jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Step2ArrayElement3jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step2ArrayElement3jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Step2ArrayElement3jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Step2ArrayElement3jTextFieldActionPerformed(evt);
            }
        });

        Step2ArrayElement4jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step2ArrayElement4jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Step3ArrayElement0jTextField.setBackground(new java.awt.Color(153, 204, 255));
        Step3ArrayElement0jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step3ArrayElement0jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Step3ArrayElement1jTextField.setBackground(new java.awt.Color(153, 204, 255));
        Step3ArrayElement1jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step3ArrayElement1jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Step3ArrayElement1jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Step3ArrayElement1jTextFieldActionPerformed(evt);
            }
        });

        Step3ArrayElement2jTextField.setBackground(new java.awt.Color(153, 204, 255));
        Step3ArrayElement2jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step3ArrayElement2jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        Step3ArrayElement3jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step3ArrayElement3jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        Step3ArrayElement3jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Step3ArrayElement3jTextFieldActionPerformed(evt);
            }
        });

        Step3ArrayElement4jTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Step3ArrayElement4jTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Selection Sort");

        key4jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        key4jLabel3.setText("key 4");

        step3jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        step3jLabel2.setText("Step 3");

        key3jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        key3jLabel3.setText("3rd Min Value");

        Step2jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Step2jLabel2.setText("Step 2");

        key2jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        key2jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        key2jLabel4.setText("2nd Min Value");

        Step1jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Step1jLabel2.setText("Step 1");

        key1jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        key1jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        key1jLabel2.setText("1st Min Value");

        ClearjButton.setBackground(new java.awt.Color(51, 153, 255));
        ClearjButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearjButton.setText("Clear");
        ClearjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ClearjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearjButtonActionPerformed(evt);
            }
        });

        ShowSSAlgorithmjButton.setBackground(new java.awt.Color(51, 153, 255));
        ShowSSAlgorithmjButton.setForeground(new java.awt.Color(255, 255, 255));
        ShowSSAlgorithmjButton.setText("Show Algorithm");
        ShowSSAlgorithmjButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ShowSSAlgorithmjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowSSAlgorithmjButtonActionPerformed(evt);
            }
        });

        sSortdemojButton.setBackground(new java.awt.Color(51, 153, 255));
        sSortdemojButton.setForeground(new java.awt.Color(255, 255, 255));
        sSortdemojButton.setText("Demo");
        sSortdemojButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sSortdemojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSortdemojButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectionSortjPanelLayout = new javax.swing.GroupLayout(SelectionSortjPanel);
        SelectionSortjPanel.setLayout(SelectionSortjPanelLayout);
        SelectionSortjPanelLayout.setHorizontalGroup(
            SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectionSortjPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(key2jLabel4)
                            .addComponent(key3jLabel3)
                            .addComponent(key1jLabel2)
                            .addComponent(Step1jLabel2)
                            .addComponent(Step2jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(key4jLabel3)
                            .addComponent(SortedarrayjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(step3jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                        .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                .addComponent(Step2ArrayElement0jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(Step2ArrayElement1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(Step2ArrayElement2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                .addComponent(Step1ArrayElement0jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(Step1ArrayElement1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(Step1ArrayElement2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                .addComponent(Step3ArrayElement0jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(Step3ArrayElement1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(Step3ArrayElement2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                        .addGap(317, 317, 317)
                                        .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                                .addComponent(Step3ArrayElement3jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(Step3ArrayElement4jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                                .addComponent(Step2ArrayElement3jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(Step2ArrayElement4jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                                .addComponent(Step1ArrayElement3jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(Step1ArrayElement4jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                        .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(smallElementjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smallElementjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(smallElementjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                .addComponent(ssArraysortedstepArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(ssArraysortedstepArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(ssArraysortedstepArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(ssArraysortedstepArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(ssArraysortedstepArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                .addComponent(ArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(ArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(ArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                .addGap(420, 420, 420)
                                .addComponent(ArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(ArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(80, 103, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectionSortjPanelLayout.createSequentialGroup()
                        .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ShowSSAlgorithmjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(ClearjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(BackjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                .addComponent(smallElementjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sSortdemojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(sSortjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(108, 108, 108))))
        );
        SelectionSortjPanelLayout.setVerticalGroup(
            SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                                .addComponent(smallElementjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Step1ArrayElement0jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step1ArrayElement2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step1ArrayElement3jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step1ArrayElement4jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step1ArrayElement1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step1jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(smallElementjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(key2jLabel4))
                                .addGap(28, 28, 28)
                                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Step2ArrayElement0jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step2ArrayElement2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step2ArrayElement3jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step2ArrayElement4jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step2ArrayElement1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step2jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(smallElementjTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(key3jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Step3ArrayElement0jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step3ArrayElement2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step3ArrayElement3jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step3ArrayElement4jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Step3ArrayElement1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(step3jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(smallElementjTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(key4jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ssArraysortedstepArrayElement2jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ssArraysortedstepArrayElement3jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ssArraysortedstepArrayElement4jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ssArraysortedstepArrayElement1jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ssArraysortedstepArrayElement0jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SortedarrayjLabel2)))
                            .addComponent(key1jLabel2)))
                    .addGroup(SelectionSortjPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sSortjButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sSortdemojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(SelectionSortjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowSSAlgorithmjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SelectionSortjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SelectionSortjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArrayElement1jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrayElement1jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArrayElement1jTextField2ActionPerformed

    private void ArrayElement3jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrayElement3jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArrayElement3jTextField2ActionPerformed

    private void sSortjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSortjButton2ActionPerformed
        try{
            JTextField Array1[];//step 1 elements

            Array1 = new JTextField[]{Step1ArrayElement0jTextField,Step1ArrayElement1jTextField,Step1ArrayElement2jTextField,
                Step1ArrayElement3jTextField,Step1ArrayElement4jTextField};
            
            JTextField Array2[];//step 2 elements

            Array2 = new JTextField[]{Step2ArrayElement0jTextField,Step2ArrayElement1jTextField,Step2ArrayElement2jTextField,
                Step2ArrayElement3jTextField,Step2ArrayElement4jTextField};
          
            JTextField Array3[];//step 3 elements

            Array3 = new JTextField[]{Step3ArrayElement0jTextField,Step3ArrayElement1jTextField,Step3ArrayElement2jTextField,
                Step3ArrayElement3jTextField,Step3ArrayElement4jTextField};
            int sortArray[]=new int[5];//elements that are entered by the user

            sortArray[0]=Integer.parseInt(ArrayElement0jTextField2.getText());
            sortArray[1]=Integer.parseInt(ArrayElement1jTextField2.getText());
            sortArray[2]=Integer.parseInt(ArrayElement2jTextField2.getText());
            sortArray[3]=Integer.parseInt(ArrayElement3jTextField2.getText());
            sortArray[4]=Integer.parseInt(ArrayElement4jTextField2.getText());

           int i,j,small,temp;
           int smallvalue []=new int[5];
           
            for(j=1;j<=sortArray.length-1;j++)//selection sort
            {   
			small=j-1;
                        for(i=j;i<sortArray.length;i++)
			{
				if(sortArray[i]<sortArray[small])
                                {
                                    small=i;
                                }
                                smallvalue[j]=sortArray[small];
                        
			}
                        
                        temp=sortArray[j-1];
			sortArray[j-1]=sortArray[small];
			sortArray[small]=temp;
                        
                        for(i=j;i<sortArray.length;i++)
                        {
                           if(j==1 && i==1)
                            {
                                smallElementjTextField.setText(Integer.toString(smallvalue[1]));
                                        
                                for(int m=0;m<Array1.length;m++)
                                {
                                        Array1[m].setText(Integer.toString(sortArray[m]));
                                        Array1[small].setBackground(Color.ORANGE);
                                }
                            }
                            if(j==2 && i==2)
                            {
                                smallElementjTextField1.setText(Integer.toString(smallvalue[2]));
                                for(int m=0;m<Array2.length;m++)
                                {
                                        Array2[m].setText(Integer.toString(sortArray[m]));
                                        Array2[small].setBackground(Color.ORANGE);
                                }
                            }
                            if(j==3 && i==3)
                            {
                                smallElementjTextField2.setText(Integer.toString(smallvalue[3]));
                                for(int m=0;m<Array3.length;m++)
                                {
                                        Array3[m].setText(Integer.toString(sortArray[m]));
                                        Array3[small].setBackground(Color.ORANGE);
                                }
                            }
                            if(j==4 && i==4)
                            {
                                 smallElementjTextField3.setText(Integer.toString(smallvalue[4]));
                            }
                        }

            }
            for(int m=0;m<sortArray.length;m++)
            {
                ssArraysortedstepArrayElement0jTextField2.setText(Integer.toString(sortArray[0]));
                ssArraysortedstepArrayElement1jTextField2.setText(Integer.toString(sortArray[1]));
                ssArraysortedstepArrayElement2jTextField2.setText(Integer.toString(sortArray[2]));
                ssArraysortedstepArrayElement3jTextField2.setText(Integer.toString(sortArray[3]));
                ssArraysortedstepArrayElement4jTextField2.setText(Integer.toString(sortArray[4]));
            }

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_sSortjButton2ActionPerformed

    private void ssArraysortedstepArrayElement0jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssArraysortedstepArrayElement0jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssArraysortedstepArrayElement0jTextField2ActionPerformed

    private void ssArraysortedstepArrayElement1jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssArraysortedstepArrayElement1jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssArraysortedstepArrayElement1jTextField2ActionPerformed

    private void ssArraysortedstepArrayElement3jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssArraysortedstepArrayElement3jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssArraysortedstepArrayElement3jTextField2ActionPerformed

    private void BackjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackjButtonActionPerformed
        MainAlgorithm ma1 = new MainAlgorithm();
        ma1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackjButtonActionPerformed

    private void Step1ArrayElement1jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Step1ArrayElement1jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Step1ArrayElement1jTextFieldActionPerformed

    private void Step1ArrayElement3jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Step1ArrayElement3jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Step1ArrayElement3jTextFieldActionPerformed

    private void Step2ArrayElement1jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Step2ArrayElement1jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Step2ArrayElement1jTextFieldActionPerformed

    private void Step2ArrayElement3jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Step2ArrayElement3jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Step2ArrayElement3jTextFieldActionPerformed

    private void Step3ArrayElement1jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Step3ArrayElement1jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Step3ArrayElement1jTextFieldActionPerformed

    private void Step3ArrayElement3jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Step3ArrayElement3jTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Step3ArrayElement3jTextFieldActionPerformed

    private void ClearjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearjButtonActionPerformed
    ArrayElement0jTextField2.setText("");
    ArrayElement1jTextField2.setText("");
    ArrayElement2jTextField2.setText("");
    ArrayElement3jTextField2.setText("");
    ArrayElement4jTextField2.setText("");
    Step1ArrayElement0jTextField.setText("");
    Step1ArrayElement1jTextField.setText("");
    Step1ArrayElement2jTextField.setText("");
    Step1ArrayElement3jTextField.setText("");
    Step1ArrayElement4jTextField.setText("");
    Step2ArrayElement0jTextField.setText("");
    Step2ArrayElement1jTextField.setText("");
    Step2ArrayElement2jTextField.setText("");
    Step2ArrayElement3jTextField.setText("");
    Step2ArrayElement4jTextField.setText("");
    Step3ArrayElement0jTextField.setText("");
    Step3ArrayElement1jTextField.setText("");
    Step3ArrayElement2jTextField.setText("");
    Step3ArrayElement3jTextField.setText("");
    Step3ArrayElement4jTextField.setText("");
    ssArraysortedstepArrayElement0jTextField2.setText("");
    ssArraysortedstepArrayElement1jTextField2.setText("");
    ssArraysortedstepArrayElement2jTextField2.setText("");
    ssArraysortedstepArrayElement3jTextField2.setText("");
    ssArraysortedstepArrayElement4jTextField2.setText("");
    smallElementjTextField.setText("");
    smallElementjTextField1.setText("");
    smallElementjTextField2.setText("");
    smallElementjTextField3.setText("");
    
    }//GEN-LAST:event_ClearjButtonActionPerformed

    private void ShowSSAlgorithmjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowSSAlgorithmjButtonActionPerformed
        AlgorithmSS A1=new AlgorithmSS();
        A1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ShowSSAlgorithmjButtonActionPerformed

    private void sSortdemojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSortdemojButtonActionPerformed
    ArrayElement0jTextField2.setText("4");
    ArrayElement1jTextField2.setText("2");
    ArrayElement2jTextField2.setText("5");
    ArrayElement3jTextField2.setText("3");
    ArrayElement4jTextField2.setText("9");
    }//GEN-LAST:event_sSortdemojButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectionSort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArrayElement0jTextField2;
    private javax.swing.JTextField ArrayElement1jTextField2;
    private javax.swing.JTextField ArrayElement2jTextField2;
    private javax.swing.JTextField ArrayElement3jTextField2;
    private javax.swing.JTextField ArrayElement4jTextField2;
    private javax.swing.JButton BackjButton;
    private javax.swing.JButton ClearjButton;
    private javax.swing.JPanel SelectionSortjPanel;
    private javax.swing.JButton ShowSSAlgorithmjButton;
    private javax.swing.JLabel SortedarrayjLabel2;
    private javax.swing.JTextField Step1ArrayElement0jTextField;
    private javax.swing.JTextField Step1ArrayElement1jTextField;
    private javax.swing.JTextField Step1ArrayElement2jTextField;
    private javax.swing.JTextField Step1ArrayElement3jTextField;
    private javax.swing.JTextField Step1ArrayElement4jTextField;
    private javax.swing.JLabel Step1jLabel2;
    private javax.swing.JTextField Step2ArrayElement0jTextField;
    private javax.swing.JTextField Step2ArrayElement1jTextField;
    private javax.swing.JTextField Step2ArrayElement2jTextField;
    private javax.swing.JTextField Step2ArrayElement3jTextField;
    private javax.swing.JTextField Step2ArrayElement4jTextField;
    private javax.swing.JLabel Step2jLabel2;
    private javax.swing.JTextField Step3ArrayElement0jTextField;
    private javax.swing.JTextField Step3ArrayElement1jTextField;
    private javax.swing.JTextField Step3ArrayElement2jTextField;
    private javax.swing.JTextField Step3ArrayElement3jTextField;
    private javax.swing.JTextField Step3ArrayElement4jTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel key1jLabel2;
    private javax.swing.JLabel key2jLabel4;
    private javax.swing.JLabel key3jLabel3;
    private javax.swing.JLabel key4jLabel3;
    private javax.swing.JButton sSortdemojButton;
    private javax.swing.JButton sSortjButton2;
    private javax.swing.JTextField smallElementjTextField;
    private javax.swing.JTextField smallElementjTextField1;
    private javax.swing.JTextField smallElementjTextField2;
    private javax.swing.JTextField smallElementjTextField3;
    private javax.swing.JTextField ssArraysortedstepArrayElement0jTextField2;
    private javax.swing.JTextField ssArraysortedstepArrayElement1jTextField2;
    private javax.swing.JTextField ssArraysortedstepArrayElement2jTextField2;
    private javax.swing.JTextField ssArraysortedstepArrayElement3jTextField2;
    private javax.swing.JTextField ssArraysortedstepArrayElement4jTextField2;
    private javax.swing.JLabel step3jLabel2;
    // End of variables declaration//GEN-END:variables
}
